# Altere para o seu usuário (geralmente root) e sua senha testada no Workbench
spring.datasource.username=root
spring.datasource.password=Wizard3.0

# Adicionamos o serverTimezone para evitar erros de conexão inicial
spring.datasource.url=jdbc:mysql://localhost:3306/controle_financeiro?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false

# Driver e Dialeto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Log para debug (ajuda a ver se a tabela foi criada)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true